apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /Users/test/ca.crt
    server: https://1.2.3.4:8443
  name: testCluster
contexts:
- context:
    cluster: testCluster
    user: testUser
    namespace: testNS
  name: test
current-context: test
preferences: {}
users:
- name: testUser
  user:
    client-certificate: /Users/test/client.crt
    client-key: /Users/test/client.key
